name: Ci with GitHub Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Spell Check Repo
        uses: crate-ci/typos@master

      - name: Package manager setup
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint
